### ISSUE TITLE
Response to Query API WebSocket subscription contains invalid URI

### ISSUE THREAD

**Issue by mgratzke** [bbc/nmos-query#3]
The "ws_href" field in the [example]( https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/examples/queryapi-v1.1-subscriptions-post-200.json)

is filled with "ws://172.29.80.52:8870/ws/?uid=7c903667-7113-4a8f-8865-1c63f9070a9e"

but in fact the implementation expects the URI

ws://172.29.80.52:8870/**x-nmos/query/v1.2/**ws/?uid=7c903667-7113-4a8f-8865-1c63f9070a9e

**Comment by simonrankine** [comment]
Hi there,

In this case it is the example that is misleading, rather than the implementation being wrong. If you look at the query API spec [here](http://amwa-tv.github.io/nmos-discovery-registration/branches/v1.2.x/html-APIs/QueryAPI.html) you'll see right at the top that we expect the API to be namespaced x-nmos/query/v1.2. I'll flag this as an issue on the spec's github.

**Comment by simonrankine** [comment]
Bug reported on IS-04 spec. here https://github.com/AMWA-TV/nmos-discovery-registration/issues/33

**Comment by mgratzke** [comment]
You are right, thank you.
